### ISSUE TITLE
Extra column decorators with conditions

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#123]
_Original author: shadypie...@gmail.com (December 20, 2011 10:05:41)_

Hello,

I have created an extra column on my datagrid and I want to put a condition upon the decorator. For example in the news datagrid on my website, I have an extra column to manage the comments, and i want to display manage link only if the news have comment. To retrieve this, I have to give the id of the news but when I use {{id}} the value is not interpreted, that is to say I get the string {{id}} and not corresponding value. Do you have some tips to get through this?

<b>Please insert the appropriate values;</b>
                    Zend Framework version: 1.11.11
ZFDatgrid Version (Bvb_Grid::getVersion()): 0.8

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=807_

**Comment by imonteiro** [comment]
_From dsamb...@gmail.com on January 05, 2012 12:44:48_
Hi Shady,
I Have used callback function to workarround this, the callback returns different html tags, in this case a class value , depending on the value of other field.
Here is a copy&paste on a place I use this:

//Example init

/*******************************
_Extra column definition
*_******************************/
$editVersionPartial = new Bvb_Grid_Extra_Column();
        $editVersionPartial
            ->setPosition('right')
            ->setName('editVersionPartial')
            ->setTitle('Capitulo Temporada')
            ->callback(array('function'=>array($this,'gridTextBoxValue'),'params'=>array('RelChapter_{{=version}}_{{=versionpartial}}_{{=chapid}}')))
            ->setDecorator("{{callback}}");

/***************************
_CallBack Definition
*_***************************/

```
public function  gridTextBoxValue($params){
    list($field,$version,$dbVersionPartial,$chapid)=explode("_",$params);
    if ( $dbVersionPartial){
        return "<div class='okcell'><input class='seasontextbox' name='".$field."_".$chapid."' value='".$dbVersionPartial."'/></div>";
    }elseif($version){
        return "<div class='warningcell'><input class='seasontextbox' name='".$field."_".$chapid."' value='".$this->scrapperResult[$version][$field]."'/></div>";
    }else{
        return "<div class='warningcell'><input class='seasontextbox' name='".$field."_".$chapid."' value=''/></div>";
    }
}
```

//Example end

I hope this inspire you
Regards

**Comment by imonteiro** [comment]
_From shadypie...@gmail.com on January 08, 2012 04:53:22_
Really nice, I'll try this way.

**Comment by imonteiro** [comment]
_From shadypie...@gmail.com on January 25, 2012 10:58:30_
So I have tried your solution, which works great… yet only if you haven't another callback on a field… which is actually the case here ! Someone has an idea to avoid this problem?

Thanks

**Comment by imonteiro** [comment]
_From ivomonte...@gmail.com on March 18, 2012 21:43:07_
That is true. However we are discussing which solution is better to solve that - #791 (  It's written in portuguese. Maybe I will translate that...).

**Comment by mystackover** [comment]
Hi,

I really appreciate your answer for callback for decorators and it really helped me.

Thanks.
