### ISSUE TITLE
Doctrine not displaying results

### ISSUE THREAD

**Issue by imonteiro** [zfdatagrid/grid#687]
_Original author: vlatko.b...@gmail.com (March 15, 2010 16:14:31)_

Hi,

I'm just trying Doctrine for the first time and I was very pleasantly
surprised :-) when I realized that zfDatagrid already has the adapter for
it. However, it is not working as it should.

This is my code:

  $grid = $this-&gt;grid();
  $tst = Doctrine_Query::create()-&gt;from(&quot;Addressbook t&quot;);
  $src = new Bvb_Grid_Source_Doctrine($tst);
  $grid-&gt;setSource($src);
  $this-&gt;view-&gt;Doctrine = $grid-&gt;deploy();

Query is executing fine, I see results if I echo them directly.
Am I missing something?

<b>What is the expected output? What do you see instead?</b>
Grid with data
Empty grid, no data in the grid

<b>Please insert the appropriate values______</b>
                   Zend Framework version: 1.10.1
  ZFDatgrid Version ($grid-&gt;getVersion()): 0.6 beta
                         Operating system: Vista
                              PHP Version: 5.2.x
                     Database and version: MySql 5.x
                         Source Adatapter: PDO

<b>Please provide any additional information below.</b>
There is no data displayed, but all the rows are present. Paging works (two
pages, Next, Previous) and even filtering works. But no data is displayed.

_Original issue: http://code.google.com/p/zfdatagrid/issues/detail?id=209_

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 15, 2010 17:01:07_
Looking into this now

**Comment by imonteiro** [comment]
_From bento.vi...@gmail.com on March 15, 2010 17:15:20_
Hi,

@Solomon

It's because there are no fields specified, in this case all fields are fetched. 

If you specify them, everything works...

$tst = Doctrine_Query::create()->select('field, field2')->from("Addressbook t");

Best Regards,
Bento Vilas Boas

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 15, 2010 18:24:45_
Hi,

I tried 
$tst = Doctrine_Query::create()->select('name,lastname,street')->from("Addressbook t");

but I'm getting strange error "Couldn't find class ".

The query returns all the fields anyway, just the values of non specified ones (like
City) is null.

When using without the select() part, the number and names of the fields are
correctly displayed in grid. Correct number of rows as well. Just no data in cells.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 15, 2010 18:51:02_
This should be fixed now, although I have no tried to move the file into trunk, if i
even have permission to do so.  But if you grab the Doctrine.php class from the
doctrine branch, it should work with out having to specify a select.

This currently works for me:
$q = Doctrine_Query::create()->from('Model_Country');

$config = new Zend_Config_Ini(AP . '/configs/grid.ini', AE);

$grid = Bvb_Grid_Data::factory('Bvb_Grid_Deploy_Table', $config);
$grid->setSource(new Bvb_Grid_Source_Doctrine($query));

$this->view->grid = $grid->deploy();

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 15, 2010 19:29:19_
Hi,

Data is displayed now. Tried with few tables and all seems correct. Thanks. :-)

However, when I try with select() clause, I receive the same error as above  (comment 3).

Also, my addressbook table has to FKs, userID and countryID and I'm receiving a 

Notice: Undefined index: join in C:...\Bvb\Grid\Source\Doctrine.php on line 680

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 15, 2010 19:39:44_
Can you provide the Doctrine_Query you are constructing?

And if you are trying to select columns from a join, you will need to reference this:

$q = Doctrine_Query::create()->from('Model_Country co')
                             ->leftJoin('co.City ci');
......
$grid->setGridColumns(array('co_code', 'co_name', 'co_continent', 'ci_name'));
$grid->updateColumn('ci_name', array('title' => 'Country'));

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 15, 2010 19:52:58_
Hi,

No, I'm just using very simple query. Attached is the code, SQL for table and Query
variable.

Would be nice if you could post/publish some example code to the trunk.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 15, 2010 20:32:24_
I cannot do anything with trunk.  Please reference the "solomonjames" branch for
working examples of Doctrine integration.

And once the Doctrine.php is updated in trunk, your issue should be fixed.

Broken : Doctrine_Query::create()->select('name,lastname,street')->from("Addressbook t");

Works : 
Doctrine_Query::create()->select('t.name,t.lastname,t.street')->from("Addressbook t");

You must specify the alias in the select

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 16, 2010 09:36:43_
Hi,

no more critical error with select('t.name,t.lastname,t.street'), but no more data
displayed either. Like above.

I also noticed that the field titles in the grid are displayed as 
'T Name' 'T Lastname' 'T Street', so translator can't find them.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 16, 2010 14:54:07_
I have confirmed this as bug, and have fixed it, please check this out.

Also reference comment #6.

If you have a query like this:
Doctrine_Query::create()->select('t.name,t.lastname,t.street')->from("Addressbook t");

If you try to do something like $grid->setGridColumns() or $grid->updateColumn() you
will need to do the following:

$grid->setGridColumns('t_name', 't_lastname', 't_street');

BUT, if you were to give your query alias' like this:
Doctrine_Query::create()->select('t.name AS name, t.lastname AS lastname, t.street AS
street')->from("Addressbook t");

You can then do:
$grid->setGridColumns('name', 'lastname', 'street');

I hope this helps.  And thank you for the help debugging.

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 16, 2010 18:00:33_
Hi,

I tried it and both versions (with select() and without it) work. 

However, 
1. I'm still getting 
   Notice: Undefined index: join in C:...\Bvb\Grid\Source\Doctrine.php on line 754
2. In query with select() (few fields):
   Field titles are still in form "T Name". It should be just "Name". No 'T' at all
   and in any form (as in 'T.Name' or 'T_Name'). Very bad for translation.
3. In query without select() (all fields):
   Field titles have changed case (e.g. phoneHome is changed to Phonehome). I do not 
   think such conversion should happen. Maybe capitalize the first letter, but 
   that's all.
4. Would it be possible to use some conversion/translation of field names "t_xxx"?
   
   Instead of 
     $grid->setGridColumns('t_name', 't_lastname', 't_street');
   use this
     $grid->setGridColumns('t.name', 't.lastname', 't.street');

The second version is quite common and, I know I'm new to Doctrine and don't know how
much work would it use, if it stays this way, there might be a need to double the
grid's layout depending on its source. I think this should be avoided.
1. I assume this field name change is happening on custom filtering and ordering as
   well. Haven't got to it yet.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 16, 2010 19:23:50_
If you could google talk, my email is solomonjames@gmail.com, please message me for a
more fluid convo.

The reason that columns are titled and selected with "t_name" or "T Name" is due to
joining.  If you specify a join, and do not provide a select, or field name alias',
you are going to get "t_name" syntax.  Why?  Well because the field needs to be
prefixed just in case there is a "name" field in the joined table.

Now if you are to provide a field alias "t.name AS name" the key is "name" and the
title would be "Name" but the field is saved as "t.name".  Why again?  Because if you
decided to order by or filter that column, i need to real column name, not the alias
in order for the query to work.

Also, in order to accomplish this, I am using Doctrine's Scalar hydration method, as
it will prefix all fields with the table alias, and will not produce a nested array,
like the Array hydration method will.  And the Datagrid needs a flat array of the
columns.

As for the undefined index error, that should be fixed now, but would not of affected
your results.

Please reference comment #6

As for #3, I am using the same method of Titleizing that owner has used, and for now
will suffice.  Maybe in the future there will be a callback, or some what to use a
custom titleize method.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 16, 2010 19:34:50_
a quick note, I am definitely up for other ways to accomplish all this without the
need to have the table alias in there, "T Name" or "t_name".  I just have yet to see
how that would occur.

I am always game for criticism and different ideas on how to accomplish this.

**Comment by imonteiro** [comment]
_From solomonj...@gmail.com on March 16, 2010 22:12:26_
ok, as per Bento's request and how his code already works.  I have re-factored it to
not do the prefix.

Doctrine_Query::create()->select('t.name,t.lastname,t.street')->from("Addressbook t");

That will now correspond to:

$grid->setGridColumns('name', 'lastname', 'street');

Unless you specify an Alias for the column.  

Note:  That if you have similar column names when you join, they will be overridden
and will need an alias to grab that.

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 17, 2010 07:06:41_
Hi,
1. Titleizing :-)
   I think that instead of using coulmnNames (lowercased), you could use fieldNames
   (original case) from query. That way after ucfirst-ing the field name, it will be the
   same as for the rest of the grid sources (e.g. phoneHome would become PhoneHome).
2. Table referencing
   I think you misunderstood what I was talking about. It is ok to reference fields by
   their table, just the syntax should change. 
   What I mean is that instead of an underscore (_), dot (.) notation should be used.
   Not t_name, but t.name.

I do not think it is bad to have the ability to specify columns by their fully
qualified name. Sometimes it might save us the need to specify aliases in selects.
Not use it if it is not needed, but use it if there is ambiguity. 

What do you and Bento think of this?

**Comment by imonteiro** [comment]
_From vlatko.b...@gmail.com on March 17, 2010 10:21:34_
I switched _columnNames and _fieldNames above in 1.

**Comment by Paul75** [comment]
In I do this : 
$grid = Bvb_Grid::factory();
$doctrineQuery = Doctrine_Query::create()->select('libelle, adresse, cp, localite')->from("Bureau");
$source = new Bvb_Grid_Source_Doctrine($doctrineQuery);
$grid->setSource($source);
$grid->setGridColumns('libelle', 'adresse', 'cp', 'localite');
$this->view->grid = $grid->deploy();

It say me : 
Fatal error: Declaration of Bvb_Grid_Source_Doctrine::getIdentifierColumns() must be compatible with that of Bvb_Grid_Source_SourceInterface::getIdentifierColumns() in C:\wamp\www\abonnementlr\library\Bvb\Grid\Source\Doctrine.php on line 13

I do all that it wrote in this post and have the same message.

Thanks
